### ISSUE TITLE
Trying to use viaIR

### ISSUE THREAD

**Issue by ta99i** [NomicFoundation/hardhat#3699]
I have some Issues when im trying to use viaIr 
The version I'm working on : hardhat@2.12.8-viair.0
my hardhat.config.js
```require("@nomicfoundation/hardhat-toolbox");

/** @type import('hardhat/config').HardhatUserConfig */
module.exports = {
  solidity: "0.8.17",
  optimizer: {
    enabled: true,
    runs: 1000,
  },
  viaIR: true,
};
```

the error i got
```
 CompilerError: Stack too deep. Try compiling with `--via-ir` (cli) or the equivalent `viaIR: true` (standard JSON) while enabling the optimizer. Otherwise, try removing local variables.
  --> contracts/xxx.sol:63:13:
   |
63 |             param[14],
   |             ^^^^^


Error HH600: Compilation failed
```

Is there a specific way or special settings in order to work on it ?

**Comment by fvictorio** [comment]
Hey @ta99i, your config should be something like this:

```
module.exports = {
  solidity: {
    version: "0.8.17",
    settings: {
      optimizer: {
        enabled: true,
        runs: 1000,
      },
      viaIR: true,
    }
  }
};
```

The `solidity: "0.8.17"` shortcut is only used when you want to use the default settings.
