### ISSUE TITLE
HH415: Ambigious source name when remappings are used within sources. 

### ISSUE THREAD

**Issue by panukettu** [NomicFoundation/hardhat#4399]
### Version of Hardhat

2.17.3

### What happened?

Hardhat does not compile a hybrid foundry project if remappings resolve to folders inside project sources.

Minimal reproduction repo: https://github.com/panukettu/hh-foundry-repro

This does work with `hardhat@2.17.1` + `@nomicfoundation/hardhat-foundry@1.0.3`.

### Minimal reproduction steps

*hardhat config*:

```
const config: HardhatUserConfig = {
  solidity: "0.8.19",
  paths: {
    sources: "./src/contracts",
  },
};
```

*foundry.toml*:

```
[profile.default]
src = 'src/contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path = 'cache_forge'
remappings = [
    'in-sources/=src/contracts/examples/',
    'outside-sources/=src/other/',
]
```

Now making an import eg. `import {Lock} from "in-sources/Lock.sol";` will result in:

`Error HH415: Two different source names ('src/contracts/examples/Lock.sol' and 'in-sources/Lock.sol') resolve to the same file`

### Search terms

remappings hardhat-foundry

**Comment by adaki2004** [comment]
As we do face the same, any update on the subject ?

**Comment by fvictorio** [comment]
For the record, the reason we do this is that source names with duplicated content can lead to weird compilation errors in some scenarios. This doesn't happen with `forge build` because in that case remappings are used, but Hardhat resolves the remappings itself.

But we should re-visit this, it might be unnecessarily limiting.

**Comment by panukettu** [comment]
> For the record, the reason we do this is that source names with duplicated content can lead to weird compilation errors in some scenarios. This doesn't happen with `forge build` because in that case remappings are used, but Hardhat resolves the remappings itself.
> 
> But we should re-visit this, it might be unnecessarily limiting.

Right.. well it would be super if it could handle either this or include paths.

**Comment by duktig666** [comment]
at DependencyGraph._addDependenciesFrom (node_modules/hardhat/src/internal/solidity/dependencyGraph.ts:170:15)

**Comment by codyx** [comment]
If you are using hardhat-foundry and imported an npm package and a foundry submodule in the same repo with different remappings, then this issue will most likely occur.

It's possible to have an external library (such as OZ) referenced as both npm package and foundry submodule as long as you make sure that import names don't clash.

For instance, with OZ contracts you can have the following package.json:
```
    "@openzeppelin/contracts": "^5.0.0",
    "@openzeppelin/contracts-upgradeable": "^5.0.0",
 ```

And install submodules with forge like this:
```
$> forge install OpenZeppelin/openzeppelin-contracts@v5.0.0
$> forge install OpenZeppelin/openzeppelin-contracts-upgradeable@v5.0.0
```

Update your remappings.txt to:
```
[...]
@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/
@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/
```

And in your Solidity files, import like this:
```
import {ERC1967Proxy} from "openzeppelin-contracts/contracts/proxy/ERC1967/ERC1967Proxy.sol";
```

That being said, I think it's cleaner to have external libraries referenced either as a foundry submodule or an npm package and not both at the same time, but in some situations you might want to do that.

**Comment by advock** [comment]
hey what's the solution to solve this  ?

**Comment by RohanNero** [comment]
Running into this issue while using foundry remappings as stated previously.

Remappings.txt: `~=src/`

`npx hardhat compile` outputs:
```shell
HardhatError: HH415: Two different source names ('src/interfaces/IERC20.sol' and '~/interfaces/IERC20.sol')
```

**Comment by panukettu** [comment]
> hey what's the solution to solve this ?

still using hardhat@2.17.1 in all projects affected by this

**Comment by Amxx** [comment]
> > hey what's the solution to solve this ?
> 
> still using hardhat@2.17.1 in all projects affected by this

hardhat@2.17.1 does not support Cancun (transient storage) :/

**Comment by panukettu** [comment]
> > > hey what's the solution to solve this ?
> > 
> > 
> > still using hardhat@2.17.1 in all projects affected by this
> 
> hardhat@2.17.1 does not support Cancun (transient storage) :/

Yes, we stopped using it but legacy is pain

**Comment by pmckelvy1** [comment]
i have a hacky solution if anyone is interested.

install and add `hardhat-preprocessor` to your hardhat config
```import "hardhat-preprocessor";```

add the following function:
```
function getRemappings() {
  return fs
    .readFileSync("remappings.txt", "utf8")
    .split("\n")
    .filter(Boolean) // remove empty lines
    .map((line) => line.trim().split("="));
}
```

and use it in the `preprocess` block
```
  preprocess: {
    eachLine: (hre) => ({
      transform: (line: string) => {
        if (line.match(/^\s*import /i)) {
          getRemappings().forEach(([find, replace]) => {
            // console.log(find, replace);
            if (line.match(find)) {
              line = line.replace(find, replace);
            }
          });
        }
        return line;
      },
    }),
  },
```

i found i needed to make sure all of my remapped routes started w/ `@` to avoid accidentally overwriting any path fragments with the same slug
