### ISSUE TITLE
`hardhat compile` randomly and quietly stops before compiling contracts

### ISSUE THREAD

**Issue by sebastiendan** [NomicFoundation/hardhat#3877]
Edit by @fvictorio: this is caused by a bug in Node v18.16.0. For a temporary workaround, downgrade your Node version to 18.15.0.

---

### Version of Hardhat

2.14.0

### What happened?

`npx hardhat compile` sometimes goes on with compiling contracts and sometimes (seems totally random) silently stops at the `Downloading compiler ...` step before any contracts are actually compiled. This issue is reproducible with no contracts already compiled and in docker.

### Minimal reproduction steps

Here's a simple repository where you can observe the problem: [repo](https://github.com/sebastiendan/hardhat-compile-issue).

This CI workflow run shows in the logs that the compilation didn't happen: [log](https://github.com/sebastiendan/hardhat-compile-issue/actions/runs/4788710757/jobs/8515780386#step:7:271).

In addition, one can run the docker container in interactive mode and manually run the `build` command to see that, again, the command sometimes doesn't build nor throws an error but simply quietly stops without compiling (same output as the CI log above):
- Run the container in interactive mode: `docker run --rm -it ghcr.io/sebastiendan/hardhat-compile-issue:main bash`
- Run the compile command: `npm run build`
- Observe sometimes an actual compilation, sometimes a quiet stop in the command execution
(run the above multiple times by exiting the container and re-running the two commands above)

### Search terms

no compilation

**Comment by fuxingloh** [comment]
See: 
- https://github.com/nodejs/node/issues/47555
- https://github.com/ada-url/ada/pull/324#event-9008153572
- https://github.com/nodejs/node/pull/47598

This is due to a regression in the latest node versions 18 and 20. Somewhere after "Downloading compiler list for platform" when trying to a compiler, it failed to download it and failed silently. 

Try to use a node version other than the latest. I'm surprised the node team hasn't done a release yet since this is a widespread issue.

**Comment by stefiix92** [comment]
@fuxingloh thanks for pointing that out, I tried node `18.12.1` and the issue disappeared!

**Comment by sebastiendan** [comment]
@fuxingloh I can confirm it works with the `18.15.0-slim` docker tag of node 👍

**Comment by fvictorio** [comment]
Wow, this is so weird. Thanks everyone for the info.

I still don't quite understand why and when this happens, but it's good to know that changing the version of node fixes the issue.

@sebastiendan I'm going to edit your issue so this information shows up first for people landing here.

**Comment by jubeira** [comment]
FWIW, Github actions is currently using `18.16.0` in Ubuntu 20 / 22 (latest) if the Node version is specified as just as `18`: https://github.com/actions/runner-images/commit/af6dd20503a81e3397993a43c30955c40ea7a248.

Specifying a different minor version (e.g `node-version: 18.15`) indeed solves the problem.

**Comment by jtakalai** [comment]
I'm getting this error (more or less, I think?), also reported in https://github.com/NomicFoundation/hardhat/issues/2569

Here's the Github Actions run: https://github.com/streamr-dev/network-contracts/actions/runs/5088395393/jobs/9144745279?pr=523#step:6:15

Explanation:
* `rm -rf artifacts && hardhat compile && rm -rf dist && tsc -p tsconfig.build.json`
  * I try to force compilation by deleting `artifacts` first (to make double sure there isn't an existing artifacts directory, so hardhat might skip compilation)
  * after, I delete `dist` just in case, and run `tsc` that outputs to `dist`
* `src/exports.ts(1,66): error TS2307: Cannot find module '../artifacts/contracts/OperatorTokenomics/Operator.sol/Operator.json' or its corresponding type declarations`
  * `tsc` says: nothing found in `artifacts`. Right after `hardhat compile`.

What makes this problem frustrating is that
* it doesn't happen every time in Github Actions
* it doesn't happen much if at all locally

**Comment by freeatnet** [comment]
I was able to add a few more logging statements through the `compile` task and reproduce the issue. It looks like response streaming [occasionally stops](https://gist.github.com/freeatnet/43c21fe1928ef632cc58105ced397c07#file-hung-log) while downloading the compiler list or the compiler itself.

There is an issue about [`stream.pipeline` ending prematurely](https://github.com/nodejs/node/issues/48406) filed in the Node repo. The [code to reproduce](https://github.com/nodejs/node/issues/48406#issuecomment-1586122983) the issue is very similar to what hardhat in the [download function](https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat-core/src/internal/util/download.ts#L58), so I assume the Node bug is the cause here. A fix (https://github.com/nodejs/node/pull/48435) is on the way.

**Comment by bdovh** [comment]
We are still affected by this issue, is Node.JS going to fix that?

**Comment by fvictorio** [comment]
Honestly, I thought they were going to release a fix sooner. I'll see if there's some workaround we can implement on our side.

**Comment by fvictorio** [comment]
Hi everyone, we just released [Hardaht v2.16.1](https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.16.1) which should fix this problem.
