### ISSUE TITLE
Error of v2.8.1 or v2.8.2: Cannot find module

### ISSUE THREAD

**Issue by gzliudan** [NomicFoundation/hardhat#2220]
When I'm using hardhat 2.8.0, I can use both below commands:
```bash
yarn test test/protocol/MatrixValuer.test.js
yarn test ./test/protocol/MatrixValuer.test.js
```
After upgrade to 2.8.1 or 2.8.2, only `yarn test test/protocol/MatrixValuer.test.js` can work, 
```text
hardhat test test/protocol/MatrixValuer.test.js
......
  6 passing (4s)
Done in 6.70s.

yarn test ./test/protocol/MatrixValuer.test.js
yarn run v1.22.17
```

But `yarn test ./test/protocol/MatrixValuer.test.js` reports below error:
```text
hardhat test ./test/protocol/MatrixValuer.test.js
......
  6 passing (4s)

An unexpected error occurred:

Error: Cannot find module './test/protocol/MatrixValuer.test.js'
Require stack:
- MY_PROJECT_DIR/node_modules/mocha/lib/mocha.js
- MY_PROJECT_DIR/node_modules/mocha/index.js
- MY_PROJECT_DIR/node_modules/hardhat/builtin-tasks/test.js
- MY_PROJECT_DIR/node_modules/hardhat/internal/core/tasks/builtin-tasks.js
- MY_PROJECT_DIR/node_modules/hardhat/internal/core/config/config-loading.js
- MY_PROJECT_DIR/node_modules/hardhat/internal/cli/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at Function.Mocha.unloadFile (MY_PROJECT_DIR/node_modules/mocha/lib/mocha.js:407:32)
    at MY_PROJECT_DIR/node_modules/mocha/lib/mocha.js:435:11
    at Array.forEach (<anonymous>)
    at Mocha.unloadFiles (MY_PROJECT_DIR/node_modules/mocha/lib/mocha.js:434:14)
    at Mocha.dispose (MY_PROJECT_DIR/node_modules/mocha/lib/mocha.js:581:8)
    at SimpleTaskDefinition.action (MY_PROJECT_DIR/node_modules/hardhat/src/builtin-tasks/test.ts:60:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'MY_PROJECT_DIR/node_modules/mocha/lib/mocha.js',
    'MY_PROJECT_DIR/node_modules/mocha/index.js',
    'MY_PROJECT_DIR/node_modules/hardhat/builtin-tasks/test.js',
    'MY_PROJECT_DIR/node_modules/hardhat/internal/core/tasks/builtin-tasks.js',
    'MY_PROJECT_DIR/node_modules/hardhat/internal/core/config/config-loading.js',
    'MY_PROJECT_DIR/node_modules/hardhat/internal/cli/cli.js'
  ]
}
error Command failed with exit code 1.
```

**Comment by 0xTimepunk** [comment]
@feuGeneA what's is the workaround for this issue?

**Comment by feuGeneA** [comment]
This will be marked fixed with the release (not just merge) of #2326 .

**Comment by alcuadrado** [comment]
This was fixed in v2.9.0.
